
services:
    app-node:
        build: .
        container_name: app-node
        ports:
            - "3000:3000"  # Mapear a porta 3000 do container para a porta 3000 na sua m치quina
        depends_on:
            - dynamodb-local  # Garante que o DynamoDB esteja rodando antes do app
        volumes:
            - .:/app
            - /app/node_modules  # Monta o diret칩rio atual da m치quina no diret칩rio /app dentro do container

    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal